2021-07-24 09:27:55,928 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 09:27:55,928 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 09:28:05,573 - INFO : This product is licensed to 
2021-07-24 09:28:05,573 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 09:28:16,855 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 09:29:12,641 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-24 09:29:14,673 - ERROR : Traceback (most recent call last):
2021-07-24 09:29:14,673 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-24 09:29:14,681 - ERROR :     explainError(control=control, error_id=error_id, error_messages_dictionary=error_messages_dictionary)
2021-07-24 09:29:14,681 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 131, in explainError
2021-07-24 09:29:14,681 - ERROR :     window.title("Error id: "+error_id)
2021-07-24 09:29:14,681 - ERROR : TypeError: can only concatenate str (not "float") to str
2021-07-24 09:52:08,114 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 09:52:08,114 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 09:52:08,219 - INFO : This product is licensed to 
2021-07-24 09:52:08,219 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 09:52:51,450 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 09:52:51,450 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 09:52:51,528 - INFO : This product is licensed to 
2021-07-24 09:52:51,528 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 09:54:03,483 - ERROR : Error calling ribbon function 'error_ribbon_functions.explainErrorWrapper'
2021-07-24 09:54:04,989 - ERROR : Traceback (most recent call last):
2021-07-24 09:54:04,989 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\error_ribbon_functions.py", line 67, in explainErrorWrapper
2021-07-24 09:54:04,990 - ERROR :     explainError(control=control, error_id=error_id, error_messages_dictionary=error_messages_dictionary)
2021-07-24 09:54:04,990 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\meta_variables.py", line 131, in explainError
2021-07-24 09:54:04,990 - ERROR :     window.title("Error id: "+error_id)
2021-07-24 09:54:04,990 - ERROR : TypeError: can only concatenate str (not "float") to str
2021-07-24 10:28:04,084 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 10:28:04,084 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 10:28:04,177 - INFO : This product is licensed to 
2021-07-24 10:28:04,177 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 10:28:33,293 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 10:28:33,293 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 10:28:33,383 - INFO : This product is licensed to 
2021-07-24 10:28:33,383 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 10:31:03,746 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 10:31:03,747 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 10:31:03,826 - INFO : This product is licensed to 
2021-07-24 10:31:03,826 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 10:31:10,208 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 10:31:10,208 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 10:31:10,300 - INFO : This product is licensed to 
2021-07-24 10:31:10,300 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 10:31:54,801 - INFO : callbacks.on_close: PyXLL is closing
2021-07-24 10:31:59,945 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 10:31:59,946 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 10:32:02,005 - INFO : This product is licensed to 
2021-07-24 10:32:02,006 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 10:32:22,729 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell'
2021-07-24 10:32:48,201 - ERROR : Traceback (most recent call last):
2021-07-24 10:32:48,201 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 48, in advanced_simulation_cell
2021-07-24 10:32:48,202 - ERROR :     result = parser.parse(adjusted_formula).evaluate(variable_dict)
2021-07-24 10:32:48,202 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 543, in parse
2021-07-24 10:32:48,202 - ERROR :     self.error_parsing(self.pos, 'unknown character')
2021-07-24 10:32:48,202 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 562, in error_parsing
2021-07-24 10:32:48,203 - ERROR :     raise Exception(self.errormsg)
2021-07-24 10:32:48,203 - ERROR : Exception: parse error [column 0]: unknown character, expression: =G2*H2+I2
2021-07-24 10:34:43,979 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell'
2021-07-24 10:34:52,384 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 10:34:52,384 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 10:34:52,505 - INFO : This product is licensed to 
2021-07-24 10:34:52,505 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 10:35:01,422 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 10:35:01,422 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 10:35:01,530 - INFO : This product is licensed to 
2021-07-24 10:35:01,530 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 10:35:06,028 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell'
2021-07-24 10:35:09,169 - ERROR : Traceback (most recent call last):
2021-07-24 10:35:09,172 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 48, in advanced_simulation_cell
2021-07-24 10:35:09,173 - ERROR :     result = parser.parse(adjusted_formula).evaluate(variable_dict)
2021-07-24 10:35:09,174 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 543, in parse
2021-07-24 10:35:09,175 - ERROR :     self.error_parsing(self.pos, 'unknown character')
2021-07-24 10:35:09,175 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 562, in error_parsing
2021-07-24 10:35:09,176 - ERROR :     raise Exception(self.errormsg)
2021-07-24 10:35:09,176 - ERROR : Exception: parse error [column 0]: unknown character, expression: =G2*H2+I2
2021-07-24 10:35:09,812 - INFO : callbacks.on_close: PyXLL is closing
2021-07-24 10:35:13,874 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 10:35:13,874 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 10:35:15,710 - INFO : This product is licensed to 
2021-07-24 10:35:15,710 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 10:35:44,998 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell'
2021-07-24 10:35:50,007 - ERROR : Traceback (most recent call last):
2021-07-24 10:35:50,007 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 48, in advanced_simulation_cell
2021-07-24 10:35:50,007 - ERROR :     result = parser.parse(adjusted_formula).evaluate(variable_dict)
2021-07-24 10:35:50,007 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 543, in parse
2021-07-24 10:35:50,022 - ERROR :     self.error_parsing(self.pos, 'unknown character')
2021-07-24 10:35:50,022 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 562, in error_parsing
2021-07-24 10:35:50,022 - ERROR :     raise Exception(self.errormsg)
2021-07-24 10:35:50,022 - ERROR : Exception: parse error [column 0]: unknown character, expression: =E7*F7+G7
2021-07-24 10:36:16,437 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 10:36:16,437 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 10:36:16,506 - INFO : This product is licensed to 
2021-07-24 10:36:16,506 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 10:36:19,146 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell'
2021-07-24 10:36:21,008 - ERROR : Traceback (most recent call last):
2021-07-24 10:36:21,008 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 48, in advanced_simulation_cell
2021-07-24 10:36:21,008 - ERROR :     
2021-07-24 10:36:21,008 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 543, in parse
2021-07-24 10:36:21,008 - ERROR :     self.error_parsing(self.pos, 'unknown character')
2021-07-24 10:36:21,008 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 562, in error_parsing
2021-07-24 10:36:21,008 - ERROR :     raise Exception(self.errormsg)
2021-07-24 10:36:21,008 - ERROR : Exception: parse error [column 0]: unknown character, expression: =E7*F7+G7
2021-07-24 10:36:24,972 - INFO : callbacks.on_close: PyXLL is closing
2021-07-24 10:36:28,903 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 10:36:28,903 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 10:36:30,709 - INFO : This product is licensed to 
2021-07-24 10:36:30,709 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 10:37:04,768 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell'
2021-07-24 10:37:06,319 - ERROR : Traceback (most recent call last):
2021-07-24 10:37:06,319 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 46, in advanced_simulation_cell
2021-07-24 10:37:06,319 - ERROR :     result = parser.parse(formula).evaluate(variable_dict)
2021-07-24 10:37:06,319 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 543, in parse
2021-07-24 10:37:06,319 - ERROR :     self.error_parsing(self.pos, 'unknown character')
2021-07-24 10:37:06,319 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 562, in error_parsing
2021-07-24 10:37:06,319 - ERROR :     raise Exception(self.errormsg)
2021-07-24 10:37:06,319 - ERROR : Exception: parse error [column 0]: unknown character, expression: =F3*G3+H3
2021-07-24 10:37:56,680 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell'
2021-07-24 10:38:18,287 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 10:38:18,287 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 10:38:18,407 - INFO : This product is licensed to 
2021-07-24 10:38:18,407 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 10:38:31,734 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell'
2021-07-24 10:38:37,044 - INFO : callbacks.on_close: PyXLL is closing
2021-07-24 10:38:42,535 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 10:38:42,535 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 10:38:44,253 - INFO : This product is licensed to 
2021-07-24 10:38:44,253 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 10:38:55,551 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 10:39:06,716 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 10:48:50,246 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell'
2021-07-24 10:48:55,882 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 10:48:55,882 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 10:48:56,011 - INFO : This product is licensed to 
2021-07-24 10:48:56,011 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 10:49:19,307 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell'
2021-07-24 10:49:21,797 - INFO : callbacks.on_close: PyXLL is closing
2021-07-24 10:49:26,091 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 10:49:26,091 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 10:49:27,862 - INFO : This product is licensed to 
2021-07-24 10:49:27,862 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 15:51:05,114 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 15:51:05,116 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 15:51:05,318 - INFO : This product is licensed to 
2021-07-24 15:51:05,318 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 15:51:07,792 - ERROR : AttributeError: module 'advanced_simulation' has no attribute 'advanced_simulation_cell_wrapper'
2021-07-24 15:51:07,793 - ERROR : Error getting ribbon callback function 'advanced_simulation.advanced_simulation_cell_wrapper'.
"module 'advanced_simulation' has no attribute 'advanced_simulation_cell_wrapper'"
2021-07-24 15:51:21,944 - ERROR : AttributeError: module 'advanced_simulation' has no attribute 'advanced_simulation_cell_wrapper'
2021-07-24 15:51:21,944 - ERROR : Error getting ribbon callback function 'advanced_simulation.advanced_simulation_cell_wrapper'.
"module 'advanced_simulation' has no attribute 'advanced_simulation_cell_wrapper'"
2021-07-24 15:51:26,124 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 15:51:26,124 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 15:51:26,214 - INFO : This product is licensed to 
2021-07-24 15:51:26,214 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 15:51:28,378 - ERROR : AttributeError: module 'advanced_simulation' has no attribute 'advanced_simulation_cell_wrapper'
2021-07-24 15:51:28,378 - ERROR : Error getting ribbon callback function 'advanced_simulation.advanced_simulation_cell_wrapper'.
"module 'advanced_simulation' has no attribute 'advanced_simulation_cell_wrapper'"
2021-07-24 15:51:51,980 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 15:51:51,980 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 15:51:52,063 - INFO : This product is licensed to 
2021-07-24 15:51:52,063 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 15:51:57,626 - ERROR : AttributeError: module 'advanced_simulation' has no attribute 'advanced_simulation_cell_wrapper'
2021-07-24 15:51:57,626 - ERROR : Error getting ribbon callback function 'advanced_simulation.advanced_simulation_cell_wrapper'.
"module 'advanced_simulation' has no attribute 'advanced_simulation_cell_wrapper'"
2021-07-24 15:51:59,624 - INFO : callbacks.on_close: PyXLL is closing
2021-07-24 15:52:07,265 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 15:52:07,265 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 15:52:10,836 - INFO : This product is licensed to 
2021-07-24 15:52:10,836 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 15:54:57,242 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 15:55:08,981 - ERROR : Traceback (most recent call last):
2021-07-24 15:55:08,981 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 79, in advanced_simulation_cell_wrapper
2021-07-24 15:55:08,990 - ERROR :     hist_data = advanced_simulation_cell(control)
2021-07-24 15:55:08,990 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 73, in advanced_simulation_cell
2021-07-24 15:55:08,991 - ERROR :     result = parser.parse(formula[1:]).evaluate(variable_dict)
2021-07-24 15:55:08,991 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 129, in evaluate
2021-07-24 15:55:08,991 - ERROR :     raise Exception('undefined variable: ' + item.index_)
2021-07-24 15:55:08,991 - ERROR : Exception: undefined variable: F2
2021-07-24 15:58:19,599 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 15:58:43,942 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 15:58:43,942 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 15:58:44,160 - INFO : This product is licensed to 
2021-07-24 15:58:44,160 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:00:59,699 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:01:04,687 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:01:04,687 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:01:04,888 - INFO : This product is licensed to 
2021-07-24 16:01:04,888 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:01:08,050 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:01:10,116 - ERROR : Traceback (most recent call last):
2021-07-24 16:01:10,126 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 79, in advanced_simulation_cell_wrapper
2021-07-24 16:01:10,127 - ERROR :     hist_data = advanced_simulation_cell(control)
2021-07-24 16:01:10,128 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 73, in advanced_simulation_cell
2021-07-24 16:01:10,129 - ERROR :     result = parser.parse(formula[1:]).evaluate(variable_dict)
2021-07-24 16:01:10,129 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 129, in evaluate
2021-07-24 16:01:10,130 - ERROR :     raise Exception('undefined variable: ' + item.index_)
2021-07-24 16:01:10,131 - ERROR : Exception: undefined variable: F2
2021-07-24 16:01:10,796 - INFO : callbacks.on_close: PyXLL is closing
2021-07-24 16:01:19,024 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:01:19,024 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:01:21,867 - INFO : This product is licensed to 
2021-07-24 16:01:21,867 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:01:33,022 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:01:44,001 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:01:54,993 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:02:05,938 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:02:17,133 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:02:28,145 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:02:39,197 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:02:50,208 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:03:01,216 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:03:12,224 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:03:23,296 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:03:34,428 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:07:16,685 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:07:20,212 - ERROR : Traceback (most recent call last):
2021-07-24 16:07:20,212 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 79, in advanced_simulation_cell_wrapper
2021-07-24 16:07:20,213 - ERROR :     hist_data = advanced_simulation_cell(control)
2021-07-24 16:07:20,213 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 62, in advanced_simulation_cell
2021-07-24 16:07:20,214 - ERROR :     variable_dict[transformed_cell_address] = advanced_simulation_cell(control=control,
2021-07-24 16:07:20,214 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 73, in advanced_simulation_cell
2021-07-24 16:07:20,214 - ERROR :     result = parser.parse(formula[1:]).evaluate(variable_dict)
2021-07-24 16:07:20,214 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 552, in parse
2021-07-24 16:07:20,215 - ERROR :     self.error_parsing(self.pos, 'parity')
2021-07-24 16:07:20,215 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 562, in error_parsing
2021-07-24 16:07:20,216 - ERROR :     raise Exception(self.errormsg)
2021-07-24 16:07:20,216 - ERROR : Exception: parse error [column 0]: parity, expression: 
2021-07-24 16:14:02,440 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:14:02,440 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:14:05,436 - INFO : This product is licensed to 
2021-07-24 16:14:05,436 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:14:43,438 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:14:45,069 - ERROR : Traceback (most recent call last):
2021-07-24 16:14:45,069 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 79, in advanced_simulation_cell_wrapper
2021-07-24 16:14:45,070 - ERROR :     hist_data = advanced_simulation_cell(control)
2021-07-24 16:14:45,070 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 62, in advanced_simulation_cell
2021-07-24 16:14:45,070 - ERROR :     variable_dict[transformed_cell_address] = advanced_simulation_cell(control=control,
2021-07-24 16:14:45,070 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 73, in advanced_simulation_cell
2021-07-24 16:14:45,071 - ERROR :     result = parser.parse(formula[1:]).evaluate(variable_dict)
2021-07-24 16:14:45,071 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 552, in parse
2021-07-24 16:14:45,071 - ERROR :     self.error_parsing(self.pos, 'parity')
2021-07-24 16:14:45,071 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 562, in error_parsing
2021-07-24 16:14:45,072 - ERROR :     raise Exception(self.errormsg)
2021-07-24 16:14:45,072 - ERROR : Exception: parse error [column 0]: parity, expression: 
2021-07-24 16:17:03,596 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:17:44,483 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:17:48,463 - ERROR : Traceback (most recent call last):
2021-07-24 16:17:48,470 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 79, in advanced_simulation_cell_wrapper
2021-07-24 16:17:48,472 - ERROR :     hist_data = advanced_simulation_cell(control)
2021-07-24 16:17:48,473 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 62, in advanced_simulation_cell
2021-07-24 16:17:48,474 - ERROR :     variable_dict[transformed_cell_address] = advanced_simulation_cell(control=control,
2021-07-24 16:17:48,474 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 73, in advanced_simulation_cell
2021-07-24 16:17:48,476 - ERROR :     result = parser.parse(formula[1:]).evaluate(variable_dict)
2021-07-24 16:17:48,477 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 508, in parse
2021-07-24 16:17:48,478 - ERROR :     self.error_parsing(self.pos, 'unexpected \",\"')
2021-07-24 16:17:48,478 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 562, in error_parsing
2021-07-24 16:17:48,480 - ERROR :     raise Exception(self.errormsg)
2021-07-24 16:17:48,480 - ERROR : Exception: parse error [column 1]: unexpected ",", expression: ,1,N
2021-07-24 16:17:56,428 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:17:56,428 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:17:56,655 - INFO : This product is licensed to 
2021-07-24 16:17:56,655 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:18:01,682 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:18:03,897 - ERROR : Traceback (most recent call last):
2021-07-24 16:18:03,897 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 79, in advanced_simulation_cell_wrapper
2021-07-24 16:18:03,899 - ERROR :     hist_data = advanced_simulation_cell(control)
2021-07-24 16:18:03,899 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 62, in advanced_simulation_cell
2021-07-24 16:18:03,901 - ERROR :     variable_dict[transformed_cell_address] = advanced_simulation_cell(control=control,
2021-07-24 16:18:03,901 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 39, in advanced_simulation_cell
2021-07-24 16:18:03,903 - ERROR :     base_items = set(re.findall('[A-Z]+[1-9]+',formula))
2021-07-24 16:18:03,904 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\re.py", line 239, in findall
2021-07-24 16:18:03,906 - ERROR :     return _compile(pattern, flags).findall(string)
2021-07-24 16:18:03,907 - ERROR : TypeError: expected string or bytes-like object
2021-07-24 16:19:13,705 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:21:30,110 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:21:47,538 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:21:47,538 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:21:47,735 - INFO : This product is licensed to 
2021-07-24 16:21:47,735 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:21:51,178 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:21:53,105 - ERROR : Traceback (most recent call last):
2021-07-24 16:21:53,106 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 79, in advanced_simulation_cell_wrapper
2021-07-24 16:21:53,107 - ERROR :     hist_data = advanced_simulation_cell(control)
2021-07-24 16:21:53,108 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 62, in advanced_simulation_cell
2021-07-24 16:21:53,109 - ERROR :     variable_dict[transformed_cell_address] = advanced_simulation_cell(control=control,
2021-07-24 16:21:53,110 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 73, in advanced_simulation_cell
2021-07-24 16:21:53,111 - ERROR :     result = parser.parse(formula[1:]).evaluate(variable_dict)
2021-07-24 16:21:53,112 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 508, in parse
2021-07-24 16:21:53,114 - ERROR :     self.error_parsing(self.pos, 'unexpected \",\"')
2021-07-24 16:21:53,114 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 562, in error_parsing
2021-07-24 16:21:53,117 - ERROR :     raise Exception(self.errormsg)
2021-07-24 16:21:53,118 - ERROR : Exception: parse error [column 1]: unexpected ",", expression: ,1,N
2021-07-24 16:23:38,619 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:23:42,627 - INFO : callbacks.on_close: PyXLL is closing
2021-07-24 16:23:49,462 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:23:49,462 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:23:52,332 - INFO : This product is licensed to 
2021-07-24 16:23:52,332 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:24:03,513 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:24:14,523 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:24:25,521 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:24:36,604 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:24:47,597 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:24:58,578 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:25:10,187 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:25:40,859 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:25:42,176 - ERROR : Traceback (most recent call last):
2021-07-24 16:25:42,176 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 79, in advanced_simulation_cell_wrapper
2021-07-24 16:25:42,177 - ERROR :     hist_data = advanced_simulation_cell(control)
2021-07-24 16:25:42,177 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 62, in advanced_simulation_cell
2021-07-24 16:25:42,178 - ERROR :     variable_dict[transformed_cell_address] = advanced_simulation_cell(control=control,
2021-07-24 16:25:42,178 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 73, in advanced_simulation_cell
2021-07-24 16:25:42,178 - ERROR :     result = parser.parse(formula[1:]).evaluate(variable_dict)
2021-07-24 16:25:42,178 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 552, in parse
2021-07-24 16:25:42,179 - ERROR :     self.error_parsing(self.pos, 'parity')
2021-07-24 16:25:42,179 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 562, in error_parsing
2021-07-24 16:25:42,179 - ERROR :     raise Exception(self.errormsg)
2021-07-24 16:25:42,179 - ERROR : Exception: parse error [column 0]: parity, expression: 
2021-07-24 16:26:28,244 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:28:10,364 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:30:12,465 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:30:13,916 - ERROR : Traceback (most recent call last):
2021-07-24 16:30:13,922 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 79, in advanced_simulation_cell_wrapper
2021-07-24 16:30:13,924 - ERROR :     hist_data = advanced_simulation_cell(control)
2021-07-24 16:30:13,925 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 62, in advanced_simulation_cell
2021-07-24 16:30:13,926 - ERROR :     variable_dict[transformed_cell_address] = advanced_simulation_cell(control=control,
2021-07-24 16:30:13,927 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 73, in advanced_simulation_cell
2021-07-24 16:30:13,929 - ERROR :     result = parser.parse(formula[1:]).evaluate(variable_dict)
2021-07-24 16:30:13,930 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 552, in parse
2021-07-24 16:30:13,932 - ERROR :     self.error_parsing(self.pos, 'parity')
2021-07-24 16:30:13,933 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 562, in error_parsing
2021-07-24 16:30:13,934 - ERROR :     raise Exception(self.errormsg)
2021-07-24 16:30:13,935 - ERROR : Exception: parse error [column 0]: parity, expression: 
2021-07-24 16:30:19,063 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:30:19,063 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:30:19,290 - INFO : This product is licensed to 
2021-07-24 16:30:19,290 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:30:22,507 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:30:23,574 - ERROR : Traceback (most recent call last):
2021-07-24 16:30:23,575 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 79, in advanced_simulation_cell_wrapper
2021-07-24 16:30:23,576 - ERROR :     hist_data = advanced_simulation_cell(control)
2021-07-24 16:30:23,577 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 62, in advanced_simulation_cell
2021-07-24 16:30:23,578 - ERROR :     variable_dict[transformed_cell_address] = advanced_simulation_cell(control=control,
2021-07-24 16:30:23,578 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 73, in advanced_simulation_cell
2021-07-24 16:30:23,579 - ERROR :     result = parser.parse(formula[1:]).evaluate(variable_dict)
2021-07-24 16:30:23,580 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 552, in parse
2021-07-24 16:30:23,581 - ERROR :     self.error_parsing(self.pos, 'parity')
2021-07-24 16:30:23,581 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 562, in error_parsing
2021-07-24 16:30:23,582 - ERROR :     raise Exception(self.errormsg)
2021-07-24 16:30:23,583 - ERROR : Exception: parse error [column 0]: parity, expression: 
2021-07-24 16:30:56,161 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:30:58,066 - INFO : callbacks.on_close: PyXLL is closing
2021-07-24 16:31:02,705 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:31:02,705 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:31:04,473 - INFO : This product is licensed to 
2021-07-24 16:31:04,473 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:31:15,725 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:31:26,740 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:31:37,763 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:31:48,766 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:31:59,734 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:32:10,900 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:32:21,867 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:32:32,866 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:32:43,842 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:32:54,799 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:33:05,747 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:33:16,695 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:33:27,649 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:33:38,729 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:33:49,753 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:34:00,718 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:34:11,703 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:34:22,738 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:34:34,038 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:48:14,394 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:48:14,394 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:48:14,499 - INFO : This product is licensed to 
2021-07-24 16:48:14,499 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:48:39,934 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:48:39,934 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:48:40,020 - INFO : This product is licensed to 
2021-07-24 16:48:40,020 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:50:41,958 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:50:41,958 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:50:42,103 - INFO : This product is licensed to 
2021-07-24 16:50:42,103 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:51:00,842 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:51:00,842 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:51:00,927 - INFO : This product is licensed to 
2021-07-24 16:51:00,927 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:51:29,339 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:51:29,339 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:51:29,434 - INFO : This product is licensed to 
2021-07-24 16:51:29,434 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:52:26,376 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:52:26,376 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:52:26,473 - INFO : This product is licensed to 
2021-07-24 16:52:26,473 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:52:41,254 - INFO : callbacks.on_close: PyXLL is closing
2021-07-24 16:52:46,505 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:52:46,506 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:52:49,664 - INFO : This product is licensed to 
2021-07-24 16:52:49,664 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:53:01,059 - WARNING : Delay in processing scheduled callbacks: Error getting Excel Window instance
2021-07-24 16:53:41,326 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:53:43,166 - ERROR : Traceback (most recent call last):
2021-07-24 16:53:43,166 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 80, in advanced_simulation_cell_wrapper
2021-07-24 16:53:43,167 - ERROR :     hist_data = advanced_simulation_cell(control)
2021-07-24 16:53:43,167 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 74, in advanced_simulation_cell
2021-07-24 16:53:43,167 - ERROR :     result = parser.parse(formula[1:]).evaluate(variable_dict)
2021-07-24 16:53:43,167 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 552, in parse
2021-07-24 16:53:43,168 - ERROR :     self.error_parsing(self.pos, 'parity')
2021-07-24 16:53:43,168 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 562, in error_parsing
2021-07-24 16:53:43,168 - ERROR :     raise Exception(self.errormsg)
2021-07-24 16:53:43,168 - ERROR : Exception: parse error [column 0]: parity, expression: 
2021-07-24 16:54:10,614 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:54:10,614 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:54:10,771 - INFO : This product is licensed to 
2021-07-24 16:54:10,771 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:54:17,977 - INFO : callbacks.on_close: PyXLL is closing
2021-07-24 16:54:23,338 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:54:23,338 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:54:25,255 - INFO : This product is licensed to 
2021-07-24 16:54:25,255 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:54:51,593 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:54:55,813 - ERROR : Traceback (most recent call last):
2021-07-24 16:54:55,814 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\lib\histograms.py", line 419, in _get_bin_edges
2021-07-24 16:54:55,814 - ERROR :     n_equal_bins = operator.index(bins)
2021-07-24 16:54:55,814 - ERROR : TypeError: 'float' object cannot be interpreted as an integer
2021-07-24 16:54:55,815 - ERROR : 
2021-07-24 16:54:55,815 - ERROR : The above exception was the direct cause of the following exception:
2021-07-24 16:54:55,815 - ERROR : 
2021-07-24 16:54:55,815 - ERROR : Traceback (most recent call last):
2021-07-24 16:54:55,815 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 85, in advanced_simulation_cell_wrapper
2021-07-24 16:54:55,815 - ERROR :     ax.hist(hist_data, bins=histogram_bins)
2021-07-24 16:54:55,815 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\__init__.py", line 1361, in inner
2021-07-24 16:54:55,816 - ERROR :     return func(ax, *map(sanitize_sequence, args), **kwargs)
2021-07-24 16:54:55,816 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\axes\_axes.py", line 6759, in hist
2021-07-24 16:54:55,817 - ERROR :     m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
2021-07-24 16:54:55,818 - ERROR :   File "<__array_function__ internals>", line 5, in histogram
2021-07-24 16:54:55,818 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\lib\histograms.py", line 793, in histogram
2021-07-24 16:54:55,819 - ERROR :     bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
2021-07-24 16:54:55,819 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\lib\histograms.py", line 421, in _get_bin_edges
2021-07-24 16:54:55,819 - ERROR :     raise TypeError(
2021-07-24 16:54:55,819 - ERROR : TypeError: `bins` must be an integer, a string, or an array
2021-07-24 16:55:12,019 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:55:12,019 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 16:55:12,111 - INFO : This product is licensed to 
2021-07-24 16:55:12,111 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 16:55:14,609 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 16:55:19,140 - ERROR : Traceback (most recent call last):
2021-07-24 16:55:19,141 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\lib\histograms.py", line 419, in _get_bin_edges
2021-07-24 16:55:19,141 - ERROR :     n_equal_bins = operator.index(bins)
2021-07-24 16:55:19,141 - ERROR : TypeError: 'float' object cannot be interpreted as an integer
2021-07-24 16:55:19,141 - ERROR : 
2021-07-24 16:55:19,141 - ERROR : The above exception was the direct cause of the following exception:
2021-07-24 16:55:19,141 - ERROR : 
2021-07-24 16:55:19,141 - ERROR : Traceback (most recent call last):
2021-07-24 16:55:19,141 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 85, in advanced_simulation_cell_wrapper
2021-07-24 16:55:19,142 - ERROR :     ax.hist(hist_data, bins=histogram_bins)
2021-07-24 16:55:19,142 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\__init__.py", line 1361, in inner
2021-07-24 16:55:19,142 - ERROR :     return func(ax, *map(sanitize_sequence, args), **kwargs)
2021-07-24 16:55:19,142 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\matplotlib\axes\_axes.py", line 6759, in hist
2021-07-24 16:55:19,144 - ERROR :     m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
2021-07-24 16:55:19,144 - ERROR :   File "<__array_function__ internals>", line 5, in histogram
2021-07-24 16:55:19,145 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\lib\histograms.py", line 793, in histogram
2021-07-24 16:55:19,146 - ERROR :     bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
2021-07-24 16:55:19,146 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\lib\histograms.py", line 421, in _get_bin_edges
2021-07-24 16:55:19,146 - ERROR :     raise TypeError(
2021-07-24 16:55:19,146 - ERROR : TypeError: `bins` must be an integer, a string, or an array
2021-07-24 16:55:20,185 - INFO : callbacks.on_close: PyXLL is closing
2021-07-24 16:55:28,756 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 16:55:28,756 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 17:02:05,916 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 17:02:05,917 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 17:02:08,702 - INFO : This product is licensed to 
2021-07-24 17:02:08,702 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 17:02:21,890 - ERROR : Error calling ribbon function 'ribbon_functions.cell_value_simulate'
2021-07-24 17:02:22,287 - ERROR : Error calling ribbon function 'ribbon_functions.cell_value_simulate'
2021-07-24 17:02:24,259 - ERROR : Traceback (most recent call last):
2021-07-24 17:02:24,259 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\ribbon_functions.py", line 402, in cell_value_simulate
2021-07-24 17:02:24,260 - ERROR :     single_simulation(control=control, address=address, id_location=id_location)
2021-07-24 17:02:24,260 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\ribbon_functions.py", line 422, in single_simulation
2021-07-24 17:02:24,261 - ERROR :     xl.ActiveSheet.Range(address).Value = block_input_simulation(control=control, range_data=address,screen_freezing=screen_freeze_disabled, id_location=id_location)
2021-07-24 17:02:24,261 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\ribbon_functions.py", line 479, in block_input_simulation
2021-07-24 17:02:24,261 - ERROR :     xl.Worksheets(distribution_sheet).Activate()
2021-07-24 17:02:24,261 - ERROR :   File "C:\Users\ethan\AppData\Local\Temp\gen_py\3.8\00020813-0000-0000-C000-000000000046x0x1x9\Sheets.py", line 120, in __call__
2021-07-24 17:02:24,262 - ERROR :     ret = self._oleobj_.InvokeTypes(0, LCID, 2, (9, 0), ((12, 1),),Index
2021-07-24 17:02:24,262 - ERROR : pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147352571), 2)
2021-07-24 17:02:34,690 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 17:02:34,690 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 17:02:34,847 - INFO : This product is licensed to 
2021-07-24 17:02:34,847 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 17:02:39,610 - INFO : callbacks.on_close: PyXLL is closing
2021-07-24 17:02:45,127 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 17:02:45,127 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 17:02:47,903 - INFO : This product is licensed to 
2021-07-24 17:02:47,903 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 17:07:16,898 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 17:07:16,898 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 17:07:16,997 - ERROR : Error reloading 'ribbon_functions'
Traceback (most recent call last):
  File "build/x64/py38/res/release/pyxll.py", line 835, in _open
  File "build/x64/py38/res/release/pyxll.py", line 8047, in reload
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\Lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\ethan\Documents\simExcel\examples\ribbon_functions.py", line 350
    ?
    ^
SyntaxError: invalid syntax
2021-07-24 17:07:19,846 - INFO : This product is licensed to 
2021-07-24 17:07:19,846 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 17:07:19,875 - ERROR : Error loading 'ribbon_functions' : invalid syntax (ribbon_functions.py, line 350)
2021-07-24 17:07:47,314 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 17:07:47,314 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 17:07:47,494 - INFO : This product is licensed to 
2021-07-24 17:07:47,494 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 17:07:56,098 - ERROR : Error calling ribbon function 'ribbon_functions.regular_simulate'
2021-07-24 17:07:57,516 - ERROR : Traceback (most recent call last):
2021-07-24 17:07:57,516 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\ribbon_functions.py", line 357, in regular_simulate
2021-07-24 17:07:57,516 - ERROR :     hist_data = hist_block_data(control=control, range_data = None, id_location=id_location, simulation_num=simulation_num, distributions_dictionary=distributions_dictionary)
2021-07-24 17:07:57,517 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\ribbon_functions.py", line 339, in hist_block_data
2021-07-24 17:07:57,517 - ERROR :     if type(data[0]) == str:
2021-07-24 17:07:57,517 - ERROR : TypeError: 'NoneType' object is not subscriptable
2021-07-24 17:08:07,974 - ERROR : Error calling ribbon function 'ribbon_functions.cell_value_simulate'
2021-07-24 17:08:09,124 - ERROR : Traceback (most recent call last):
2021-07-24 17:08:09,124 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\ribbon_functions.py", line 403, in cell_value_simulate
2021-07-24 17:08:09,125 - ERROR :     single_simulation(control=control, address=address, id_location=id_location)
2021-07-24 17:08:09,125 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\ribbon_functions.py", line 423, in single_simulation
2021-07-24 17:08:09,125 - ERROR :     xl.ActiveSheet.Range(address).Value = block_input_simulation(control=control, range_data=address,screen_freezing=screen_freeze_disabled, id_location=id_location)
2021-07-24 17:08:09,125 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\ribbon_functions.py", line 487, in block_input_simulation
2021-07-24 17:08:09,126 - ERROR :     if type(data[0]) == str:
2021-07-24 17:08:09,126 - ERROR : TypeError: 'NoneType' object is not subscriptable
2021-07-24 17:08:55,459 - INFO : 
------------------------------------------------------------------------------
  PyXLL 

  Version          5.1.1
  Buildtime        2021-04-28 17:21
  Python version   3.8
  Excel version    16.0 (64 bit)

  www.pyxll.com
------------------------------------------------------------------------------
2021-07-24 17:08:55,460 - WARNING : Python executable 'C:\Program Files\Python38\python.exe' does not exist.
2021-07-24 17:08:55,636 - INFO : This product is licensed to 
2021-07-24 17:08:55,636 - INFO : The license will expire on 2021-08-21 (28 days left)
2021-07-24 17:09:13,650 - ERROR : Error calling ribbon function 'advanced_simulation.advanced_simulation_cell_wrapper'
2021-07-24 17:09:17,665 - ERROR : Traceback (most recent call last):
2021-07-24 17:09:17,665 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 81, in advanced_simulation_cell_wrapper
2021-07-24 17:09:17,666 - ERROR :     hist_data = advanced_simulation_cell(control)
2021-07-24 17:09:17,666 - ERROR :   File "C:\Users\ethan\Documents\simExcel\examples\advanced_simulation.py", line 75, in advanced_simulation_cell
2021-07-24 17:09:17,667 - ERROR :     result = parser.parse(formula[1:]).evaluate(variable_dict)
2021-07-24 17:09:17,667 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 552, in parse
2021-07-24 17:09:17,667 - ERROR :     self.error_parsing(self.pos, 'parity')
2021-07-24 17:09:17,668 - ERROR :   File "C:\Users\ethan\AppData\Local\Programs\Python\Python38\lib\site-packages\py_expression_eval\__init__.py", line 562, in error_parsing
2021-07-24 17:09:17,668 - ERROR :     raise Exception(self.errormsg)
2021-07-24 17:09:17,668 - ERROR : Exception: parse error [column 0]: parity, expression: 
